// src/lib/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { LayoutDashboard, Layers, Plus, Settings, LogOut } from 'lucide-svelte';
	import type { SupabaseClient } from '@supabase/supabase-js';

	let { supabase }: { supabase: SupabaseClient } = $props();

	const links = [
		{ href: '/', label: 'Dashboard', icon: LayoutDashboard },
		{ href: '/decks', label: 'Decks', icon: Layers },
		{ href: '/create', label: 'New Deck', icon: Plus },
		{ href: '/settings', label: 'Settings', icon: Settings }
	];

	async function signOut() {
		await supabase.auth.signOut();
		goto('/login');
	}
</script>

<aside class="flex h-full w-60 flex-col border-r border-gray-200 bg-white">
	<div class="flex items-center gap-2 border-b border-gray-200 px-5 py-4">
		<span class="text-xl font-bold text-brand-600">Axonote</span>
	</div>

	<nav class="flex flex-1 flex-col gap-1 p-3">
		{#each links as link}
			<a
				href={link.href}
				class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors
					{page.url.pathname === link.href
					? 'bg-brand-50 text-brand-700'
					: 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}"
			>
				<link.icon size={18} />
				{link.label}
			</a>
		{/each}
	</nav>

	<div class="border-t border-gray-200 p-3">
		<button
			onclick={signOut}
			class="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-50 hover:text-gray-900"
		>
			<LogOut size={18} />
			Sign out
		</button>
	</div>
</aside>

// src/components/layout/Sidebar.tsx
import { Link, useNavigate } from '@tanstack/react-router'
import { LayoutDashboard, BookOpen, PlusCircle, Settings, LogOut, Play } from 'lucide-react'
import { supabase } from '../../lib/supabase'


const navItems = [
    { label: 'Dashboard', icon: LayoutDashboard, to: '/' },
    { label: 'Study', icon: Play, to: '/decks/$deckId/study', params: { deckId: 'all' } },
    { label: 'My Decks', icon: BookOpen, to: '/decks' },
    { label: 'Create Deck', icon: PlusCircle, to: '/create' },
]

export function Sidebar() {
    const navigate = useNavigate()

    const handleLogout = async () => {
        await supabase.auth.signOut()
        navigate({ to: '/login' })
    }

    return (
        <aside className="hidden md:flex flex-col w-64 bg-white border-r border-slate-200">
            <div className="p-6">
                <h1 className="text-xl font-bold text-brand-700">Axonote</h1>
            </div>

            <nav className="flex-1 px-4 space-y-1">
                {navItems.map((item) => (
                    <Link
                        key={item.to}
                        to={item.to}
                        activeProps={{
                            className: 'bg-brand-50 text-brand-700 font-semibold',
                        }}
                        className="flex items-center px-3 py-2 text-sm text-slate-600 rounded-lg hover:bg-slate-50 transition-colors"
                    >
                        <item.icon className="w-5 h-5 mr-3" />
                        {item.label}
                    </Link>
                ))}
            </nav>

            <div className="p-4 border-t border-slate-200">
                <button className="flex items-center w-full px-3 py-2 text-sm text-slate-600 rounded-lg hover:bg-slate-50 transition-colors">
                    <Settings className="w-5 h-5 mr-3" />
                    Settings
                </button>
                <button
                    onClick={handleLogout}
                    className="flex items-center w-full px-3 py-2 text-sm text-red-600 rounded-lg hover:bg-red-50 transition-colors mt-1"
                >
                    <LogOut className="w-5 h-5 mr-3" />
                    Logout
                </button>
            </div>
        </aside>
    )
}
