// src/routes/create.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useState } from 'react'
import { GenerationForm } from '../components/GenerationForm'
import { createDeck } from '../lib/db'
import { supabase } from '../lib/supabase'
import type { SourceType } from '../types/index'
import { Sparkles } from 'lucide-react'

export const Route = createFileRoute('/create')({
    component: CreateDeck,
})

function CreateDeck() {
    const navigate = useNavigate()
    const [isProcessing, setIsProcessing] = useState(false)
    const [error, setError] = useState<string | null>(null)

    const handleGenerate = async (data: { type: SourceType; title: string; content: string | File }) => {
        setIsProcessing(true)
        setError(null)
        try {
            const { data: { user } } = await supabase.auth.getUser()
            if (!user) throw new Error('Not authenticated')

            const description = data.type === 'TOPIC'
                ? (data.content as string)
                : `Generated from PDF: ${(data.content as File).name}`

            await createDeck(user.id, data.title, description)
            navigate({ to: '/decks' })
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to create deck')
        } finally {
            setIsProcessing(false)
        }
    }

    return (
        <div className="max-w-2xl mx-auto space-y-8 mt-4">
            <header className="text-center mb-10">
                <div className="w-16 h-16 bg-brand-50 rounded-full flex items-center justify-center mx-auto mb-4 border border-brand-100">
                    <Sparkles className="w-8 h-8 text-brand-500" />
                </div>
                <h1 className="text-3xl font-bold tracking-tight text-ink-900">Create New Deck</h1>
                <p className="text-ink-400 mt-2 text-sm max-w-sm mx-auto">Upload a document or provide a topic and our AI will extract key concepts into a study deck.</p>
            </header>

            {error && (
                <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-sm text-red-700">
                    {error}
                </div>
            )}

            <GenerationForm onGenerate={handleGenerate} isProcessing={isProcessing} />
        </div>
    )
}

// src/routes/(app)/create/+page.svelte
<script lang="ts">
	import { goto, invalidateAll } from '$app/navigation';
	import { createDeck } from '$lib/db';

	let { data } = $props();

	let title = $state('');
	let description = $state('');
	let loading = $state(false);
	let error = $state('');

	async function handleCreate(e: SubmitEvent) {
		e.preventDefault();
		loading = true;
		error = '';

		try {
			const user = data.user;
			if (!user) return;

			await createDeck(data.supabase, user.id, title, description || undefined);
			await invalidateAll();
			goto('/decks');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to create deck';
		} finally {
			loading = false;
		}
	}
</script>

<div class="mx-auto max-w-lg">
	<h1 class="mb-6 text-2xl font-bold text-gray-900">Create deck</h1>

	<form onsubmit={handleCreate} class="space-y-4 rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-200">
		{#if error}
			<p class="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600">{error}</p>
		{/if}

		<div>
			<label for="title" class="mb-1 block text-sm font-medium text-gray-700">Title</label>
			<input
				id="title"
				type="text"
				bind:value={title}
				required
				placeholder="e.g. Spanish Vocabulary"
				class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none"
			/>
		</div>

		<div>
			<label for="description" class="mb-1 block text-sm font-medium text-gray-700">
				Description <span class="text-gray-400">(optional)</span>
			</label>
			<textarea
				id="description"
				bind:value={description}
				rows="3"
				placeholder="What is this deck about?"
				class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none"
			></textarea>
		</div>

		<div class="flex gap-3">
			<a
				href="/decks"
				class="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-center text-sm font-medium text-gray-700 hover:bg-gray-50"
			>
				Cancel
			</a>
			<button
				type="submit"
				disabled={loading}
				class="flex-1 rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 disabled:opacity-50"
			>
				{loading ? 'Creating...' : 'Create deck'}
			</button>
		</div>
	</form>
</div>
